CREATE TABLE users(id SERIAL PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password TEXT NOT NULL,wallet NUMERIC DEFAULT 1000);
CREATE TABLE players(id SERIAL PRIMARY KEY,api_id INT,name VARCHAR(255),position VARCHAR(10),price NUMERIC);
CREATE TABLE leagues(id SERIAL PRIMARY KEY,name VARCHAR(255),entry_fee NUMERIC);
CREATE TABLE user_lineups(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id),players JSONB);